### ISSUE TITLE
quando si cerca senza inserire una chiave si comporta male

### ISSUE THREAD

**Issue by forobliot** [unimi-ctu/ArielPortal#143]
perchè viene interpretato come 'undefinited'

**Comment by mk-krispi** [comment]
credo di aver capito, grazie a decinaia di gugolate, che il problema dipenda dal fatto che gli scope sono gerarchici. Quindi, quando nell'ng-model di quicksearch.html si mette il riferimento a qsKeyword, quello che succede è che per la modifica del valore viene creata una nuova proprietà in $scope e non viene utilizzata quella presente in  $rootScope.
Per risolvere questo problema ci sono due strade (per ora ho utilizzato la prima)
* usare sempre il wrapper model. Cioè al posto di usare direttamente qsKeyword, bisogna usare [qualcosa].nomevariabile. http://thenittygritty.co/angularjs-pitfalls-using-scopes - Quindi ho usato globalVars.qsKeyword in tutti i punti dove veniva utilizzato solo qsKeyword. E automagically ha iniziato a funzionare. Non funziona solo in caso si acceda direttamente alla pagina "ricerca veloce siti" e si inserisca una parola chiave nella textbox della pagina. Se invece si utilizza PRIMA la textbox presente nella sidebar, allora funzionerà anche al contrario (cioè l'inserimento di una parola chiave nella textbox della pagina quicksearch provoca la modifica della textbox nella sidebar)
* una seconda soluzione che viene utilizzata è inserire un ng-change nell'input della pagina quicksearch e nell'ng-change modificare la variabile del rootscope assegnandola uguale alla nuova variabile creata nello scope. Ho inserito anche questa parte di codice, ma l'assegnamento della variabile è commentato.
angular.module('portalApp')
  .controller('QuicksearchCtrl', function ($scope, $rootScope) {
		$scope.updateRootScopeProp = function()  {
			//$rootScope.qsKeyword = $scope.qsKeyword;
		};
  });

**Comment by forobliot** [comment]
sicuramente sbaglio, ma se scrivi:

    <input type="text" class="form-control" id="keyword" placeholder="Inserisci parola chiave" ng-model="$root.qsKeyword">

al posto di

    <input type="text" class="form-control" id="keyword" placeholder="Inserisci parola chiave" ng-model="qsKeyword">

non basta? fammi sapere...

è normale che lo scope nasconda le variabili del rootscope ma si puo' comunque risalire la catena

**Comment by mk-krispi** [comment]
sì, potrebbe bastare. Avevo trovato un post sull'utilizzo di $root, ma avevo inteso che si potesse utilizzare solo nella parte controller (js) e non nella parte view (html).
Provo.

**Comment by mk-krispi** [comment]
sì $root.qsKeyword funziona!
